baseurl = "https://workshop.netlify.com"
googleAnalytics = ""
languageCode = "ru-ua"
paginate = "6"
summaryLength = "10"
theme = "parsa-hugo"
title = "Печать на одежде, шелкография и шелкотрафаретная печать | Workshop Print Харьков"
[[menu.main]]
hasChildren = true
name = "Homepage"
url = ""
weight = 1
[[menu.main]]
name = "Homepage 1"
parent = "Homepage"
url = "homepage/home-1"
[[menu.main]]
name = "Homepage 2"
parent = "Homepage"
url = "homepage/home-2"
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Contact"
url = "contact"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "Гвардейцев Широнинцев 83/26"
author = "WorkShop Print"
author_image = "images/banner-img.png"
bio = "Печать шелкотрафарет на одежде,ткани, крое, футболки, свитшот, худи, пакетах, коже, визитки, сублимация на ткани. Отличное качество принта,  высокое качество материала, приятные цены. Брендирование одежды и не только… Мастерская шелкографии Workshop Print."
contact_form_action = "#send"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](https://themefisher.com)"
description = "This is meta description"
email = "workshopprint.ua@gmail.com"
home = "Home"
layout = "2"
logo = "images/logo.png"
mobile = "0976970424"
preloader = true
search = false
[params.cookies]
enable = true
expire_days = "2"
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-facebook"
link = "https://facebook.com/themefisher"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
